/**
 * @TYPES
 * ==============================================
 * 
 */




/**
 * @TYPES
 * ===============================================
 * QUESTIONS
 */
export const FETCH_ALL_QUESTIONS = 'FETCH_ALL_QUESTIONS'
export const FETCH_ALL_FACILITIES = 'FETCH_ALL_FACILITIES'
export const FETCH_ALL_REGISTER_USERS = 'FETCH_ALL_REGISTER_USERS'
export const FETCH_ALL_DOCTORS = 'FETCH_ALL_DOCTORS'
export const FETCH_ALL_HEALTHTIPS = 'FETCH_ALL_HEALTHTIPS'
export const CREATE_HEALTH_TYPE = 'CREATE_HEALTH_TYPE'
export const CREATE_HEALTH_TIPS = 'CREATE_HEALTH_TIPS'
export const DELETE_HEALTH_TIPS = 'DELETE_HEALTH_TIPS'
export const FETCH_ALL_HEALTHTIPSTYPE = 'FETCH_ALL_HEALTHTIPSTYPE'
export const UPDATE_HEALTH_TIPS_TYPE = 'UPDATE_HEALTH_TIPS_TYPE'

